version: 1.0.{build}
os: Visual Studio 2015
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: $(appveyor_build_version)
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-$(APPVEYOR_REPO_COMMIT)'
build:
  project: Indexer.sln
  verbosity: minimal
artifacts:
- path: Output/$(Configuration)
  name: Indexer-v$(appveyor_build_version)
deploy: off